<#
.SYNOPSIS
    Rasterise the Conda Manager icons (resources/icon.png, resources/icon-256.png, ...).

.DESCRIPTION
    The design master is resources/icon.svg: a dark gradient rounded tile with a
    green "C" ring (opening to the right) and a centered white AI sparkle.
    This script draws the PNG bitmaps with System.Drawing using the same
    geometry, so when the SVG geometry or colors change, update the defaults
    below and run it again.

    The Activity Bar icon resources/activitybar.svg is a hand-written 24x24
    single-color vector (the VS Code spec requires a single color); it is not
    generated by this script.

    NOTE: keep this file ASCII-only. Windows PowerShell 5.1 mis-decodes UTF-8
    files without a BOM, which breaks the parser.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts/make-icon.ps1
    Writes resources/icon.png (128) and resources/icon-256.png (256).

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts/make-icon.ps1 -Sizes 128,256,512
    Also writes resources/icon-512.png.
#>
[CmdletBinding()]
param(
    # Output directory; defaults to <repo>/resources
    [string]$OutDir,
    # Edge lengths in pixels; 128 is written as icon.png, others as icon-<size>.png
    [int[]]$Sizes = @(128, 256),
    # Background gradient (top-left -> bottom-right)
    [string]$Bg1 = '#1B2A22',
    [string]$Bg2 = '#0B110D',
    # "C" ring color
    [string]$LetterColor = '#5BD24A',
    # AI sparkle color
    [string]$SparkColor = '#FFFFFF'
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

if (-not $OutDir) {
    $root = Split-Path $PSScriptRoot -Parent
    $OutDir = Join-Path $root 'resources'
}
if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Path $OutDir -Force | Out-Null }

function ConvertTo-IconColor([string]$hex) { [System.Drawing.ColorTranslator]::FromHtml($hex) }

function New-RoundedRectPath([single]$x, [single]$y, [single]$w, [single]$h, [single]$r) {
    $p = New-Object System.Drawing.Drawing2D.GraphicsPath
    $d = $r * 2
    $p.AddArc($x, $y, $d, $d, 180, 90)
    $p.AddArc($x + $w - $d, $y, $d, $d, 270, 90)
    $p.AddArc($x + $w - $d, $y + $h - $d, $d, $d, 0, 90)
    $p.AddArc($x, $y + $h - $d, $d, $d, 90, 90)
    $p.CloseFigure()
    return $p
}

# Four-point sparkle: outer points at top/right/bottom/left, pinched in between.
function New-SparklePath([single]$cx, [single]$cy, [single]$radius, [double]$waist = 0.3) {
    $points = New-Object 'System.Collections.Generic.List[System.Drawing.PointF]'
    for ($k = 0; $k -lt 4; $k++) {
        $outerAngle = (-90 + 90 * $k) * [Math]::PI / 180
        $innerAngle = (-45 + 90 * $k) * [Math]::PI / 180
        $innerRadius = $radius * $waist
        $ox = [single]($cx + $radius * [Math]::Cos($outerAngle))
        $oy = [single]($cy + $radius * [Math]::Sin($outerAngle))
        $ix = [single]($cx + $innerRadius * [Math]::Cos($innerAngle))
        $iy = [single]($cy + $innerRadius * [Math]::Sin($innerAngle))
        $points.Add([System.Drawing.PointF]::new($ox, $oy))
        $points.Add([System.Drawing.PointF]::new($ix, $iy))
    }
    $p = New-Object System.Drawing.Drawing2D.GraphicsPath
    $p.AddPolygon($points.ToArray())
    return $p
}

function New-Icon([int]$size) {
    # All geometry is designed on a 128 grid and scaled proportionally.
    $scale = $size / 128.0
    $bmp = New-Object System.Drawing.Bitmap($size, $size)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
    $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $g.PixelOffsetMode = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality

    $rect = New-Object System.Drawing.RectangleF(0, 0, $size, $size)
    $bgPath = New-RoundedRectPath 0 0 $size $size (28 * $scale)

    $bgBrush = New-Object System.Drawing.Drawing2D.LinearGradientBrush(
        $rect, (ConvertTo-IconColor $Bg1), (ConvertTo-IconColor $Bg2),
        [System.Drawing.Drawing2D.LinearGradientMode]::ForwardDiagonal)
    $g.FillPath($bgBrush, $bgPath)

    # Subtle highlight in the top-left corner.
    $sheen = New-Object System.Drawing.Drawing2D.LinearGradientBrush(
        $rect, [System.Drawing.Color]::FromArgb(38, 255, 255, 255), [System.Drawing.Color]::FromArgb(0, 255, 255, 255),
        [System.Drawing.Drawing2D.LinearGradientMode]::ForwardDiagonal)
    $g.FillPath($sheen, $bgPath)

    # "C" ring: center (64,64), radius 31, stroke 14, round caps, opening right.
    $pen = New-Object System.Drawing.Pen((ConvertTo-IconColor $LetterColor), (14 * $scale))
    $pen.StartCap = [System.Drawing.Drawing2D.LineCap]::Round
    $pen.EndCap = [System.Drawing.Drawing2D.LineCap]::Round
    $cx = 64 * $scale
    $cy = 64 * $scale
    $radius = 31 * $scale
    $arcRect = New-Object System.Drawing.RectangleF(($cx - $radius), ($cy - $radius), ($radius * 2), ($radius * 2))
    $g.DrawArc($pen, $arcRect, 320, -280)

    # Centered sparkle. NOTE: PowerShell variable names are case-insensitive,
    # so do not reuse the $SparkColor name here.
    $sparklePath = New-SparklePath $cx $cy (19 * $scale)
    $sparkleBrush = New-Object System.Drawing.SolidBrush((ConvertTo-IconColor $SparkColor))
    $g.FillPath($sparkleBrush, $sparklePath)

    $g.Dispose()
    $bgBrush.Dispose()
    $sheen.Dispose()
    $pen.Dispose()
    $sparkleBrush.Dispose()
    $bgPath.Dispose()
    $sparklePath.Dispose()
    return $bmp
}

foreach ($size in $Sizes) {
    if ($size -eq 128) { $name = 'icon.png' } else { $name = "icon-$size.png" }
    $out = Join-Path $OutDir $name
    $img = New-Icon $size
    $img.Save($out, [System.Drawing.Imaging.ImageFormat]::Png)
    $img.Dispose()
    Write-Output "wrote $out ($size x $size)"
}
